.PHONY: clean All

All:
	@echo "----------Building project:[ max_subarray_problem - Debug ]----------"
	@cd "max_subarray_problem" && "$(MAKE)" -f  "max_subarray_problem.mk"
clean:
	@echo "----------Cleaning project:[ max_subarray_problem - Debug ]----------"
	@cd "max_subarray_problem" && "$(MAKE)" -f  "max_subarray_problem.mk" clean
