.PHONY: clean All

All:
	@echo "----------Building project:[ insertionsort - Debug ]----------"
	@cd "insertionsort" && "$(MAKE)" -f  "insertionsort.mk"
clean:
	@echo "----------Cleaning project:[ insertionsort - Debug ]----------"
	@cd "insertionsort" && "$(MAKE)" -f  "insertionsort.mk" clean
